theme: jekyll-theme-cayman
title: Code 201 Reading Notes
description: This website has reading notes for the CodeFellows Code 201 course - taken in January 2020. 

#Table of Contents

##* __Reading 1
- Notes:
##* __Reading 2
- Notes:
##* __Reading 3
- Notes:
##* __Reading 4
- Notes:
##* __Reading 5
- Notes:
##* __Reading 6
- Notes:
##* __Reading 7
- Notes:
##* __Reading 8
- Notes:
##* __Reading 9
- Notes:
##* __Reading 10
- Notes:
##* __Reading 11
- Notes:
##* __Reading 12
- Notes:
##* __Reading 13
- Notes:
##* __Reading 14
- Notes:
##* __Reading 15
- Notes:





>The past is in your head,
>The future is in your hands.
